### ISSUE TITLE
请教一下：PrinterShare驱动问题

### ISSUE THREAD

**Issue by JakeWoki** [wbzlop/Android-Wifi-Printer#1]
里面有很多驱动，这个驱动怎么开发的？根据不同打印机的文档？没弄过这块，不知道怎么开发这些驱动

**Comment by wbzlop** [comment]
没有继续深入研究了。
关键应该在文末说的 PCL 数据格式。
我的理解：pcl数据就是你说的“驱动”。
希望你能的研究能有突破～

**Comment by wbzlop** [comment]
> 里面有很多驱动，这个驱动怎么开发的？根据不同打印机的文档？没弄过这块，不知道怎么开发这些驱动

没有继续深入研究了。
关键应该在文末说的 PCL 数据格式。
我的理解：pcl数据就是你说的“驱动”。
希望你能的研究能有突破～
